/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SignoutCallbackOidcRouteImport } from './routes/signout-callback-oidc'
import { Route as SigninOidcRouteImport } from './routes/signin-oidc'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BffLoginRouteImport } from './routes/bff/login'
import { Route as AuthDashboardRouteImport } from './routes/_auth.dashboard'
import { Route as AuthChooseHabitsRouteImport } from './routes/_auth.choose-habits'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignoutCallbackOidcRoute = SignoutCallbackOidcRouteImport.update({
  id: '/signout-callback-oidc',
  path: '/signout-callback-oidc',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninOidcRoute = SigninOidcRouteImport.update({
  id: '/signin-oidc',
  path: '/signin-oidc',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BffLoginRoute = BffLoginRouteImport.update({
  id: '/bff/login',
  path: '/bff/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthChooseHabitsRoute = AuthChooseHabitsRouteImport.update({
  id: '/choose-habits',
  path: '/choose-habits',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/error': typeof ErrorRoute
  '/signin-oidc': typeof SigninOidcRoute
  '/signout-callback-oidc': typeof SignoutCallbackOidcRoute
  '/signup': typeof SignupRoute
  '/choose-habits': typeof AuthChooseHabitsRoute
  '/dashboard': typeof AuthDashboardRoute
  '/bff/login': typeof BffLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/error': typeof ErrorRoute
  '/signin-oidc': typeof SigninOidcRoute
  '/signout-callback-oidc': typeof SignoutCallbackOidcRoute
  '/signup': typeof SignupRoute
  '/choose-habits': typeof AuthChooseHabitsRoute
  '/dashboard': typeof AuthDashboardRoute
  '/bff/login': typeof BffLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_auth': typeof AuthRouteWithChildren
  '/error': typeof ErrorRoute
  '/signin-oidc': typeof SigninOidcRoute
  '/signout-callback-oidc': typeof SignoutCallbackOidcRoute
  '/signup': typeof SignupRoute
  '/_auth/choose-habits': typeof AuthChooseHabitsRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/bff/login': typeof BffLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/error'
    | '/signin-oidc'
    | '/signout-callback-oidc'
    | '/signup'
    | '/choose-habits'
    | '/dashboard'
    | '/bff/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/error'
    | '/signin-oidc'
    | '/signout-callback-oidc'
    | '/signup'
    | '/choose-habits'
    | '/dashboard'
    | '/bff/login'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_auth'
    | '/error'
    | '/signin-oidc'
    | '/signout-callback-oidc'
    | '/signup'
    | '/_auth/choose-habits'
    | '/_auth/dashboard'
    | '/bff/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AuthRoute: typeof AuthRouteWithChildren
  ErrorRoute: typeof ErrorRoute
  SigninOidcRoute: typeof SigninOidcRoute
  SignoutCallbackOidcRoute: typeof SignoutCallbackOidcRoute
  SignupRoute: typeof SignupRoute
  BffLoginRoute: typeof BffLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signout-callback-oidc': {
      id: '/signout-callback-oidc'
      path: '/signout-callback-oidc'
      fullPath: '/signout-callback-oidc'
      preLoaderRoute: typeof SignoutCallbackOidcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin-oidc': {
      id: '/signin-oidc'
      path: '/signin-oidc'
      fullPath: '/signin-oidc'
      preLoaderRoute: typeof SigninOidcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bff/login': {
      id: '/bff/login'
      path: '/bff/login'
      fullPath: '/bff/login'
      preLoaderRoute: typeof BffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/choose-habits': {
      id: '/_auth/choose-habits'
      path: '/choose-habits'
      fullPath: '/choose-habits'
      preLoaderRoute: typeof AuthChooseHabitsRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthChooseHabitsRoute: typeof AuthChooseHabitsRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthChooseHabitsRoute: AuthChooseHabitsRoute,
  AuthDashboardRoute: AuthDashboardRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AuthRoute: AuthRouteWithChildren,
  ErrorRoute: ErrorRoute,
  SigninOidcRoute: SigninOidcRoute,
  SignoutCallbackOidcRoute: SignoutCallbackOidcRoute,
  SignupRoute: SignupRoute,
  BffLoginRoute: BffLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
