/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SignoutCallbackOidcRouteImport } from './routes/signout-callback-oidc'
import { Route as SigninOidcRouteImport } from './routes/signin-oidc'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BffSplatRouteImport } from './routes/bff/$'
import { Route as ApiSplatRouteImport } from './routes/api/$'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignoutCallbackOidcRoute = SignoutCallbackOidcRouteImport.update({
  id: '/signout-callback-oidc',
  path: '/signout-callback-oidc',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninOidcRoute = SigninOidcRouteImport.update({
  id: '/signin-oidc',
  path: '/signin-oidc',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BffSplatRoute = BffSplatRouteImport.update({
  id: '/bff/$',
  path: '/bff/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/signin-oidc': typeof SigninOidcRoute
  '/signout-callback-oidc': typeof SignoutCallbackOidcRoute
  '/signup': typeof SignupRoute
  '/api/$': typeof ApiSplatRoute
  '/bff/$': typeof BffSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/signin-oidc': typeof SigninOidcRoute
  '/signout-callback-oidc': typeof SignoutCallbackOidcRoute
  '/signup': typeof SignupRoute
  '/api/$': typeof ApiSplatRoute
  '/bff/$': typeof BffSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/signin-oidc': typeof SigninOidcRoute
  '/signout-callback-oidc': typeof SignoutCallbackOidcRoute
  '/signup': typeof SignupRoute
  '/api/$': typeof ApiSplatRoute
  '/bff/$': typeof BffSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/signin-oidc'
    | '/signout-callback-oidc'
    | '/signup'
    | '/api/$'
    | '/bff/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/signin-oidc'
    | '/signout-callback-oidc'
    | '/signup'
    | '/api/$'
    | '/bff/$'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/signin-oidc'
    | '/signout-callback-oidc'
    | '/signup'
    | '/api/$'
    | '/bff/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  SigninOidcRoute: typeof SigninOidcRoute
  SignoutCallbackOidcRoute: typeof SignoutCallbackOidcRoute
  SignupRoute: typeof SignupRoute
  ApiSplatRoute: typeof ApiSplatRoute
  BffSplatRoute: typeof BffSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signout-callback-oidc': {
      id: '/signout-callback-oidc'
      path: '/signout-callback-oidc'
      fullPath: '/signout-callback-oidc'
      preLoaderRoute: typeof SignoutCallbackOidcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin-oidc': {
      id: '/signin-oidc'
      path: '/signin-oidc'
      fullPath: '/signin-oidc'
      preLoaderRoute: typeof SigninOidcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bff/$': {
      id: '/bff/$'
      path: '/bff/$'
      fullPath: '/bff/$'
      preLoaderRoute: typeof BffSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  SigninOidcRoute: SigninOidcRoute,
  SignoutCallbackOidcRoute: SignoutCallbackOidcRoute,
  SignupRoute: SignupRoute,
  ApiSplatRoute: ApiSplatRoute,
  BffSplatRoute: BffSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
