/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SignoutCallbackOidcRouteImport } from './routes/signout-callback-oidc'
import { Route as SigninOidcRouteImport } from './routes/signin-oidc'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BffLoginRouteImport } from './routes/bff/login'
import { Route as AuthSetTempoRouteImport } from './routes/_auth.set-tempo'
import { Route as AuthQuestsRouteImport } from './routes/_auth.quests'
import { Route as AuthDashboardRouteImport } from './routes/_auth.dashboard'
import { Route as AuthCreateQuestRouteImport } from './routes/_auth.create-quest'
import { Route as AuthChooseHabitsRouteImport } from './routes/_auth.choose-habits'
import { Route as ApiBillingWebhookRouteImport } from './routes/api/billing.webhook'
import { Route as AuthQuestQuestIdRouteImport } from './routes/_auth.quest.$questId'
import { Route as AuthHabitHabitIdRouteImport } from './routes/_auth.habit.$habitId'

const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignoutCallbackOidcRoute = SignoutCallbackOidcRouteImport.update({
  id: '/signout-callback-oidc',
  path: '/signout-callback-oidc',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninOidcRoute = SigninOidcRouteImport.update({
  id: '/signin-oidc',
  path: '/signin-oidc',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BffLoginRoute = BffLoginRouteImport.update({
  id: '/bff/login',
  path: '/bff/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSetTempoRoute = AuthSetTempoRouteImport.update({
  id: '/set-tempo',
  path: '/set-tempo',
  getParentRoute: () => AuthRoute,
} as any)
const AuthQuestsRoute = AuthQuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCreateQuestRoute = AuthCreateQuestRouteImport.update({
  id: '/create-quest',
  path: '/create-quest',
  getParentRoute: () => AuthRoute,
} as any)
const AuthChooseHabitsRoute = AuthChooseHabitsRouteImport.update({
  id: '/choose-habits',
  path: '/choose-habits',
  getParentRoute: () => AuthRoute,
} as any)
const ApiBillingWebhookRoute = ApiBillingWebhookRouteImport.update({
  id: '/api/billing/webhook',
  path: '/api/billing/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthQuestQuestIdRoute = AuthQuestQuestIdRouteImport.update({
  id: '/quest/$questId',
  path: '/quest/$questId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthHabitHabitIdRoute = AuthHabitHabitIdRouteImport.update({
  id: '/habit/$habitId',
  path: '/habit/$habitId',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/account': typeof AccountRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signin-oidc': typeof SigninOidcRoute
  '/signout-callback-oidc': typeof SignoutCallbackOidcRoute
  '/signup': typeof SignupRoute
  '/success': typeof SuccessRoute
  '/choose-habits': typeof AuthChooseHabitsRoute
  '/create-quest': typeof AuthCreateQuestRoute
  '/dashboard': typeof AuthDashboardRoute
  '/quests': typeof AuthQuestsRoute
  '/set-tempo': typeof AuthSetTempoRoute
  '/bff/login': typeof BffLoginRoute
  '/habit/$habitId': typeof AuthHabitHabitIdRoute
  '/quest/$questId': typeof AuthQuestQuestIdRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/account': typeof AccountRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signin-oidc': typeof SigninOidcRoute
  '/signout-callback-oidc': typeof SignoutCallbackOidcRoute
  '/signup': typeof SignupRoute
  '/success': typeof SuccessRoute
  '/choose-habits': typeof AuthChooseHabitsRoute
  '/create-quest': typeof AuthCreateQuestRoute
  '/dashboard': typeof AuthDashboardRoute
  '/quests': typeof AuthQuestsRoute
  '/set-tempo': typeof AuthSetTempoRoute
  '/bff/login': typeof BffLoginRoute
  '/habit/$habitId': typeof AuthHabitHabitIdRoute
  '/quest/$questId': typeof AuthQuestQuestIdRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_auth': typeof AuthRouteWithChildren
  '/account': typeof AccountRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signin-oidc': typeof SigninOidcRoute
  '/signout-callback-oidc': typeof SignoutCallbackOidcRoute
  '/signup': typeof SignupRoute
  '/success': typeof SuccessRoute
  '/_auth/choose-habits': typeof AuthChooseHabitsRoute
  '/_auth/create-quest': typeof AuthCreateQuestRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/quests': typeof AuthQuestsRoute
  '/_auth/set-tempo': typeof AuthSetTempoRoute
  '/bff/login': typeof BffLoginRoute
  '/_auth/habit/$habitId': typeof AuthHabitHabitIdRoute
  '/_auth/quest/$questId': typeof AuthQuestQuestIdRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/account'
    | '/error'
    | '/login'
    | '/pricing'
    | '/signin-oidc'
    | '/signout-callback-oidc'
    | '/signup'
    | '/success'
    | '/choose-habits'
    | '/create-quest'
    | '/dashboard'
    | '/quests'
    | '/set-tempo'
    | '/bff/login'
    | '/habit/$habitId'
    | '/quest/$questId'
    | '/api/billing/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/account'
    | '/error'
    | '/login'
    | '/pricing'
    | '/signin-oidc'
    | '/signout-callback-oidc'
    | '/signup'
    | '/success'
    | '/choose-habits'
    | '/create-quest'
    | '/dashboard'
    | '/quests'
    | '/set-tempo'
    | '/bff/login'
    | '/habit/$habitId'
    | '/quest/$questId'
    | '/api/billing/webhook'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_auth'
    | '/account'
    | '/error'
    | '/login'
    | '/pricing'
    | '/signin-oidc'
    | '/signout-callback-oidc'
    | '/signup'
    | '/success'
    | '/_auth/choose-habits'
    | '/_auth/create-quest'
    | '/_auth/dashboard'
    | '/_auth/quests'
    | '/_auth/set-tempo'
    | '/bff/login'
    | '/_auth/habit/$habitId'
    | '/_auth/quest/$questId'
    | '/api/billing/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AuthRoute: typeof AuthRouteWithChildren
  AccountRoute: typeof AccountRoute
  ErrorRoute: typeof ErrorRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  SigninOidcRoute: typeof SigninOidcRoute
  SignoutCallbackOidcRoute: typeof SignoutCallbackOidcRoute
  SignupRoute: typeof SignupRoute
  SuccessRoute: typeof SuccessRoute
  BffLoginRoute: typeof BffLoginRoute
  ApiBillingWebhookRoute: typeof ApiBillingWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signout-callback-oidc': {
      id: '/signout-callback-oidc'
      path: '/signout-callback-oidc'
      fullPath: '/signout-callback-oidc'
      preLoaderRoute: typeof SignoutCallbackOidcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin-oidc': {
      id: '/signin-oidc'
      path: '/signin-oidc'
      fullPath: '/signin-oidc'
      preLoaderRoute: typeof SigninOidcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bff/login': {
      id: '/bff/login'
      path: '/bff/login'
      fullPath: '/bff/login'
      preLoaderRoute: typeof BffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/set-tempo': {
      id: '/_auth/set-tempo'
      path: '/set-tempo'
      fullPath: '/set-tempo'
      preLoaderRoute: typeof AuthSetTempoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/quests': {
      id: '/_auth/quests'
      path: '/quests'
      fullPath: '/quests'
      preLoaderRoute: typeof AuthQuestsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/create-quest': {
      id: '/_auth/create-quest'
      path: '/create-quest'
      fullPath: '/create-quest'
      preLoaderRoute: typeof AuthCreateQuestRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/choose-habits': {
      id: '/_auth/choose-habits'
      path: '/choose-habits'
      fullPath: '/choose-habits'
      preLoaderRoute: typeof AuthChooseHabitsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/billing/webhook': {
      id: '/api/billing/webhook'
      path: '/api/billing/webhook'
      fullPath: '/api/billing/webhook'
      preLoaderRoute: typeof ApiBillingWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/quest/$questId': {
      id: '/_auth/quest/$questId'
      path: '/quest/$questId'
      fullPath: '/quest/$questId'
      preLoaderRoute: typeof AuthQuestQuestIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/habit/$habitId': {
      id: '/_auth/habit/$habitId'
      path: '/habit/$habitId'
      fullPath: '/habit/$habitId'
      preLoaderRoute: typeof AuthHabitHabitIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthChooseHabitsRoute: typeof AuthChooseHabitsRoute
  AuthCreateQuestRoute: typeof AuthCreateQuestRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthQuestsRoute: typeof AuthQuestsRoute
  AuthSetTempoRoute: typeof AuthSetTempoRoute
  AuthHabitHabitIdRoute: typeof AuthHabitHabitIdRoute
  AuthQuestQuestIdRoute: typeof AuthQuestQuestIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthChooseHabitsRoute: AuthChooseHabitsRoute,
  AuthCreateQuestRoute: AuthCreateQuestRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthQuestsRoute: AuthQuestsRoute,
  AuthSetTempoRoute: AuthSetTempoRoute,
  AuthHabitHabitIdRoute: AuthHabitHabitIdRoute,
  AuthQuestQuestIdRoute: AuthQuestQuestIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AuthRoute: AuthRouteWithChildren,
  AccountRoute: AccountRoute,
  ErrorRoute: ErrorRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  SigninOidcRoute: SigninOidcRoute,
  SignoutCallbackOidcRoute: SignoutCallbackOidcRoute,
  SignupRoute: SignupRoute,
  SuccessRoute: SuccessRoute,
  BffLoginRoute: BffLoginRoute,
  ApiBillingWebhookRoute: ApiBillingWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
